name: CI Back-end
on:
  push:
    paths:
      - 'sgcmapi/**'
    branches:
      - '**'
      - '!main'
  pull_request:
    paths:
      - 'sgcmapi/**'

# permissions:
#   contents: write
#   pull-requests: write
#   issues: write
#   packages: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: sgcmapi/
        run: mvn compile
  test:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: sgcmapi/
        run: mvn test
  merge:
    permissions: write-all
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge Branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}         
